import type { NextPage } from 'next'
import Head from 'next/head'
import Hero from '../components/hero_section/Hero'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>La Favola</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />
      </main>
    </div>
  )
}

export default Home
