import type { NextPage } from 'next'
import Head from 'next/head'
import ContactUs from '../components/Contact'
import Hero from '../components/hero_section/Hero'
import Images from '../components/Images'
import Menu from '../components/Menu'
import Reviews from '../components/Reviews'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>La Favola</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />
        <Menu />
        <Images />
        <Reviews />
        <ContactUs />
      </main>
    </div>
  )
}

export default Home
