import type { NextPage } from 'next'
import Head from 'next/head'
import ContactUs from '../components/Contact'
import Hero from '../components/hero_section/Hero'
import Images from '../components/Images'
import Menu from '../components/Menu'
import Reviews from '../components/Reviews'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>La Favola</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />



      <main className="pt-16">
        <section id="hero">
          <Hero />
        </section>
        <section id="menu">
          <Menu />
        </section>
        <section id="gallery">
          <Images />
        </section>
        <section id="reviews">
          <Reviews />
        </section>
        <section id="contact">
          <ContactUs />
        </section>
      </main>

        <div className="bg-red-500 text-center text-xl p-8">
            <p className="text-white font-bold">
                Nous serons fermés pour congés annuels du 3 août au 31 août inclus. <br />
                Bonne vacances à tous !
            </p>
        </div>

      <Footer />
    </div>
  )
}

export default Home
